name: Update PAC File

on:
  schedule:
    - cron: "19 * * * *"
    - cron: "43 * * * *"
  workflow_dispatch:

permissions:
  contents: write  # Needed to allow a git push from the Action

concurrency:
  group: pac-update
  cancel-in-progress: true  # True to cancel ongoing runs instead of queuing them

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Generate PAC file
        run: python generate_pac.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add proxy.pac .htaccess
          git diff --cached --quiet || git commit -m "Update PAC file"
          git push
